import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import computer from "../public/computer.png";
import code from "../public/code.png";
import coding from "../public/coding.svg";
import me from "../public/me.jpg";
import { useState } from "react";

//const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Danny Roberts Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-700">
          <section className=" min-h-screen pb-10">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className=" text-xl "></h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-xl dark:text-white"
                  />
                </li>
                <li>
                  <a
                    download
                    className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="DannyRobertsCV2023.pdf"
                  >
                    Download CV
                  </a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-5 ">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-300">
                Danny Roberts
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                Aspiring Web Developer
              </h3>
              <p className="text-md py-5 leading-8 text-gray=800 md:text-xl max-w-xl mx-auto dark:text-white">
                Hi, I'm a Software Engineering graduate with a passion for all
                things web. I currently have 4+ years in the software industry
                and I'm looking to kickstart my Web Dev career.
                <br />
                <br /> Download my CV above, or continue reading to learn more.
              </p>
            </div>
            <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-5 mx-auto overflow-hidden md:h-96 md:w-96">
              <Image src={me} fill objectFit="cover" />
            </div>
            <div className="text-5xl flex justify-center gap-8 pt-10 text-gray-600 dark:text-white">
              <AiFillTwitterCircle />
              <a
                href="https://www.linkedin.com/in/daniel-roberts315/"
                target={"_blank"}
              >
                <AiFillLinkedin />
              </a>
            </div>
          </section>

          <section>
            <hr />
            <div>
              <h3 className="text-3xl py-5 text-center text-teal-600 md:text-left dark:text-white">
                More about me...
              </h3>
              {/* <p className="text-md py-1 leading-8 text-gray-800">
                Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                Lorem Ipsum Lorem Ipsum Ipsum Lorem Ipsum Ipsum Lorem Ipsum
              </p> */}
            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg px-10 pb-10 rounded-xl my-10 dark:bg-slate-600 md:w-96">
                <Image
                  src={computer}
                  width={150}
                  height={150}
                  className="m-auto"
                />
                <h3 className="text-lg font-medium  pb-2 dark:text-white">
                  Web Design
                </h3>
                <h4 className="py-4 text-teal-600 dark:text-teal-300">
                  I have experience in:
                </h4>
                <p className="text-gray-800 py-1 dark:text-white">HTML & CSS</p>
                <p className="text-gray-800 py-1 dark:text-white">JavaScript</p>
                <p className="text-gray-800 py-1 dark:text-white">
                  React - Next.js
                </p>
                <p className="text-gray-800 py-1 dark:text-white">
                  Tailwind CSS
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-600 md:w-96">
                <Image src={code} width={100} height={100} className="m-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                  Skills
                </h3>
                <h4 className="py-4 text-teal-600 dark:text-teal-300">
                  Other skills that I have:
                </h4>
                <p className="text-gray-800 py-1 dark:text-white">SQL</p>
                <p className="text-gray-800 py-1 dark:text-white">
                  OOP Programming
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-600 md:w-96">
                <Image
                  src={coding}
                  width={100}
                  height={100}
                  className="m-auto"
                />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                  Projects
                </h3>
                <h4 className="py-4 text-teal-600 dark:text-teal-300">
                  Projects which I am working on:
                </h4>
                <p className="text-gray-800 py-1 dark:text-white">
                  This website!
                </p>
                <p className="text-gray-800 py-1 dark:text-white">
                  Meal planning react.js app
                </p>
              </div>
            </div>
            <hr />
            <div>
              <h3 className="text-3xl py-5 text-center text-teal-600 md:text-left dark:text-white">
                Contact
              </h3>
              <p className="text-md py-5 leading-8 text-gray=800 md:text-lg md:text-left dark:text-white">
                To contact me, please feel free to drop me an email at{" "}
                <a
                  href="mailto:danny.roberts315@gmail.com"
                  className="text-blue-500"
                >
                  danny.roberts315@gmail.com
                </a>
                <br />
                <br />I look forward to hearing from you.
              </p>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
